// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbsqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type MealTagEnum string

const (
	MealTagEnumBreakfast MealTagEnum = "breakfast"
	MealTagEnumLunch     MealTagEnum = "lunch"
	MealTagEnumDinner    MealTagEnum = "dinner"
	MealTagEnumSnack     MealTagEnum = "snack"
	MealTagEnumOther     MealTagEnum = "other"
)

func (e *MealTagEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MealTagEnum(s)
	case string:
		*e = MealTagEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for MealTagEnum: %T", src)
	}
	return nil
}

type NullMealTagEnum struct {
	MealTagEnum MealTagEnum
	Valid       bool // Valid is true if MealTagEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMealTagEnum) Scan(value interface{}) error {
	if value == nil {
		ns.MealTagEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MealTagEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMealTagEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MealTagEnum), nil
}

type MoodTypeEnum string

const (
	MoodTypeEnumEnergy       MoodTypeEnum = "energy"
	MoodTypeEnumFogHeaviness MoodTypeEnum = "fog_heaviness"
	MoodTypeEnumStress       MoodTypeEnum = "stress"
	MoodTypeEnumMotivation   MoodTypeEnum = "motivation"
)

func (e *MoodTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MoodTypeEnum(s)
	case string:
		*e = MoodTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for MoodTypeEnum: %T", src)
	}
	return nil
}

type NullMoodTypeEnum struct {
	MoodTypeEnum MoodTypeEnum
	Valid        bool // Valid is true if MoodTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMoodTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.MoodTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MoodTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMoodTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MoodTypeEnum), nil
}

type MoodCheckin struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	MoodType     MoodTypeEnum
	Quality      int16
	Note         pgtype.Text
	TimestampUtc pgtype.Timestamptz
}

type NutritionEntry struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	TimestampUtc pgtype.Timestamptz
	MealTag      NullMealTagEnum
	Calories     pgtype.Numeric
	ProteinG     pgtype.Numeric
	FiberG       pgtype.Numeric
	AddedSugarG  pgtype.Numeric
	CarbsG       pgtype.Numeric
}

type User struct {
	ID        pgtype.UUID
	Email     pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type UserSetting struct {
	UserID   pgtype.UUID
	Timezone string
}
