// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: mood.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMoodCheckin = `-- name: CreateMoodCheckin :one
INSERT INTO mood_checkins (id, user_id, mood_type, quality, note, timestamp_utc)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, mood_type, quality, note, timestamp_utc
`

type CreateMoodCheckinParams struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	MoodType     MoodTypeEnum
	Quality      int16
	Note         pgtype.Text
	TimestampUtc pgtype.Timestamptz
}

func (q *Queries) CreateMoodCheckin(ctx context.Context, arg CreateMoodCheckinParams) (MoodCheckin, error) {
	row := q.db.QueryRow(ctx, createMoodCheckin,
		arg.ID,
		arg.UserID,
		arg.MoodType,
		arg.Quality,
		arg.Note,
		arg.TimestampUtc,
	)
	var i MoodCheckin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MoodType,
		&i.Quality,
		&i.Note,
		&i.TimestampUtc,
	)
	return i, err
}

const deleteMoodCheckin = `-- name: DeleteMoodCheckin :execrows
DELETE FROM mood_checkins
WHERE id = $1 AND user_id = $2
`

type DeleteMoodCheckinParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteMoodCheckin(ctx context.Context, arg DeleteMoodCheckinParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMoodCheckin, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMoodCheckin = `-- name: GetMoodCheckin :one
SELECT id, user_id, mood_type, quality, note, timestamp_utc FROM mood_checkins
WHERE id = $1 AND user_id = $2
`

type GetMoodCheckinParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetMoodCheckin(ctx context.Context, arg GetMoodCheckinParams) (MoodCheckin, error) {
	row := q.db.QueryRow(ctx, getMoodCheckin, arg.ID, arg.UserID)
	var i MoodCheckin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MoodType,
		&i.Quality,
		&i.Note,
		&i.TimestampUtc,
	)
	return i, err
}

const listMoodCheckins = `-- name: ListMoodCheckins :many
SELECT id, user_id, mood_type, quality, note, timestamp_utc FROM mood_checkins
WHERE user_id = $1
  AND ($2::timestamptz IS NULL OR timestamp_utc >= $2)
  AND ($3::timestamptz IS NULL OR timestamp_utc <= $3)
  AND ($4::mood_type_enum IS NULL OR mood_type = $4)
  AND ($5::timestamptz IS NULL OR (timestamp_utc, id) < ($5, $6))
ORDER BY timestamp_utc DESC, id DESC
LIMIT $7
`

type ListMoodCheckinsParams struct {
	UserID       pgtype.UUID
	Column2      pgtype.Timestamptz
	Column3      pgtype.Timestamptz
	Column4      MoodTypeEnum
	Column5      pgtype.Timestamptz
	TimestampUtc pgtype.Timestamptz
	Limit        int32
}

func (q *Queries) ListMoodCheckins(ctx context.Context, arg ListMoodCheckinsParams) ([]MoodCheckin, error) {
	rows, err := q.db.Query(ctx, listMoodCheckins,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.TimestampUtc,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MoodCheckin
	for rows.Next() {
		var i MoodCheckin
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MoodType,
			&i.Quality,
			&i.Note,
			&i.TimestampUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
