// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: nutrition.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNutritionEntry = `-- name: CreateNutritionEntry :one
INSERT INTO nutrition_entries (
  id, user_id, timestamp_utc, meal_tag, calories, protein_g, fiber_g, added_sugar_g, carbs_g
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, timestamp_utc, meal_tag, calories, protein_g, fiber_g, added_sugar_g, carbs_g
`

type CreateNutritionEntryParams struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	TimestampUtc pgtype.Timestamptz
	MealTag      NullMealTagEnum
	Calories     pgtype.Numeric
	ProteinG     pgtype.Numeric
	FiberG       pgtype.Numeric
	AddedSugarG  pgtype.Numeric
	CarbsG       pgtype.Numeric
}

func (q *Queries) CreateNutritionEntry(ctx context.Context, arg CreateNutritionEntryParams) (NutritionEntry, error) {
	row := q.db.QueryRow(ctx, createNutritionEntry,
		arg.ID,
		arg.UserID,
		arg.TimestampUtc,
		arg.MealTag,
		arg.Calories,
		arg.ProteinG,
		arg.FiberG,
		arg.AddedSugarG,
		arg.CarbsG,
	)
	var i NutritionEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TimestampUtc,
		&i.MealTag,
		&i.Calories,
		&i.ProteinG,
		&i.FiberG,
		&i.AddedSugarG,
		&i.CarbsG,
	)
	return i, err
}

const deleteNutritionEntry = `-- name: DeleteNutritionEntry :execrows
DELETE FROM nutrition_entries
WHERE id = $1 AND user_id = $2
`

type DeleteNutritionEntryParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteNutritionEntry(ctx context.Context, arg DeleteNutritionEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNutritionEntry, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNutritionEntry = `-- name: GetNutritionEntry :one
SELECT id, user_id, timestamp_utc, meal_tag, calories, protein_g, fiber_g, added_sugar_g, carbs_g FROM nutrition_entries
WHERE id = $1 AND user_id = $2
`

type GetNutritionEntryParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetNutritionEntry(ctx context.Context, arg GetNutritionEntryParams) (NutritionEntry, error) {
	row := q.db.QueryRow(ctx, getNutritionEntry, arg.ID, arg.UserID)
	var i NutritionEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TimestampUtc,
		&i.MealTag,
		&i.Calories,
		&i.ProteinG,
		&i.FiberG,
		&i.AddedSugarG,
		&i.CarbsG,
	)
	return i, err
}

const listNutritionEntries = `-- name: ListNutritionEntries :many
SELECT id, user_id, timestamp_utc, meal_tag, calories, protein_g, fiber_g, added_sugar_g, carbs_g FROM nutrition_entries
WHERE user_id = $1
  AND ($2::timestamptz IS NULL OR timestamp_utc >= $2)
  AND ($3::timestamptz IS NULL OR timestamp_utc <= $3)
  AND ($4::meal_tag_enum IS NULL OR meal_tag = $4)
  AND ($5::timestamptz IS NULL OR (timestamp_utc, id) < ($5, $6))
ORDER BY timestamp_utc DESC, id DESC
LIMIT $7
`

type ListNutritionEntriesParams struct {
	UserID       pgtype.UUID
	Column2      pgtype.Timestamptz
	Column3      pgtype.Timestamptz
	Column4      MealTagEnum
	Column5      pgtype.Timestamptz
	TimestampUtc pgtype.Timestamptz
	Limit        int32
}

func (q *Queries) ListNutritionEntries(ctx context.Context, arg ListNutritionEntriesParams) ([]NutritionEntry, error) {
	rows, err := q.db.Query(ctx, listNutritionEntries,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.TimestampUtc,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NutritionEntry
	for rows.Next() {
		var i NutritionEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TimestampUtc,
			&i.MealTag,
			&i.Calories,
			&i.ProteinG,
			&i.FiberG,
			&i.AddedSugarG,
			&i.CarbsG,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
