// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: summary.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const dailyMacroTotals = `-- name: DailyMacroTotals :many
SELECT
  (timestamp_utc AT TIME ZONE $2)::date AS date_local,
  SUM(calories)::double precision AS calories,
  SUM(protein_g)::double precision AS protein_g,
  SUM(fiber_g)::double precision AS fiber_g,
  SUM(added_sugar_g)::double precision AS added_sugar_g,
  SUM(carbs_g)::double precision AS carbs_g
FROM nutrition_entries
WHERE user_id = $1
  AND (timestamp_utc AT TIME ZONE $2)::date BETWEEN $3::date AND $4::date
GROUP BY 1
ORDER BY 1 ASC
`

type DailyMacroTotalsParams struct {
	UserID   pgtype.UUID
	Timezone pgtype.Interval
	Column3  pgtype.Date
	Column4  pgtype.Date
}

type DailyMacroTotalsRow struct {
	DateLocal   pgtype.Date
	Calories    float64
	ProteinG    float64
	FiberG      float64
	AddedSugarG float64
	CarbsG      float64
}

func (q *Queries) DailyMacroTotals(ctx context.Context, arg DailyMacroTotalsParams) ([]DailyMacroTotalsRow, error) {
	rows, err := q.db.Query(ctx, dailyMacroTotals,
		arg.UserID,
		arg.Timezone,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyMacroTotalsRow
	for rows.Next() {
		var i DailyMacroTotalsRow
		if err := rows.Scan(
			&i.DateLocal,
			&i.Calories,
			&i.ProteinG,
			&i.FiberG,
			&i.AddedSugarG,
			&i.CarbsG,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dailyMoodAverages = `-- name: DailyMoodAverages :many
SELECT
  (timestamp_utc AT TIME ZONE $2)::date AS date_local,
  mood_type,
  AVG(quality)::double precision AS avg_quality
FROM mood_checkins
WHERE user_id = $1
  AND (timestamp_utc AT TIME ZONE $2)::date BETWEEN $3::date AND $4::date
GROUP BY 1, 2
ORDER BY 1 ASC
`

type DailyMoodAveragesParams struct {
	UserID   pgtype.UUID
	Timezone pgtype.Interval
	Column3  pgtype.Date
	Column4  pgtype.Date
}

type DailyMoodAveragesRow struct {
	DateLocal  pgtype.Date
	MoodType   MoodTypeEnum
	AvgQuality float64
}

func (q *Queries) DailyMoodAverages(ctx context.Context, arg DailyMoodAveragesParams) ([]DailyMoodAveragesRow, error) {
	rows, err := q.db.Query(ctx, dailyMoodAverages,
		arg.UserID,
		arg.Timezone,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyMoodAveragesRow
	for rows.Next() {
		var i DailyMoodAveragesRow
		if err := rows.Scan(&i.DateLocal, &i.MoodType, &i.AvgQuality); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userTimezone = `-- name: UserTimezone :one
SELECT timezone FROM user_settings WHERE user_id = $1
`

func (q *Queries) UserTimezone(ctx context.Context, userID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, userTimezone, userID)
	var timezone string
	err := row.Scan(&timezone)
	return timezone, err
}
